version: "3.7"
services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8001:81"
      - "8002:82"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:cached
      - ./www:/www

  php74:
    image: php:7.4-fpm
    volumes:
      - ./www/:/var/www/html/:cached
      - ./php/preload.ini:/usr/local/etc/php/conf.d/preload.ini
    expose:
      - 9000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
  php741:
    image: php:7.4-fpm
    volumes:
      - ./www/:/var/www/html/:cached
    expose:
      - 9000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
  php73:
    image: php:7.3.9-fpm
    volumes:
      - ./www/:/var/www/html/:cached
    expose:
      - 9000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M