version: "3.7"
services:

  nginx:
    build:
      context: .
      dockerfile: VeryNginx/Dockerfile
#    image: nginx:latest
    ports:
      - "8000:80"
      - "8001:81"
      - "8002:82"
      - "8003:83"
    volumes:
#      - ./nginx/conf.d/default.conf:/opt/verynginx/verynginx/nginx_conf/in_http_block.conf:cached
      - ./www:/www

  php74:
    image: php:7.4-fpm
    volumes:
      - ./www/:/var/www/html/:cached
      - ./php/preload.ini:/usr/local/etc/php/conf.d/preload.ini
      - ./php/fpm.conf:/usr/local/etc/php-fpm.d/zfpm.conf
    expose:
      - 9000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
  php741:
    image: php:7.4-fpm
    volumes:
      - ./www/:/var/www/html/:cached
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php/fpm.conf:/usr/local/etc/php-fpm.d/zfpm.conf
    expose:
      - 9000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
  php73:
    image: php:7.3.9-fpm
    volumes:
      - ./www/:/var/www/html/:cached
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php/fpm.conf:/usr/local/etc/php-fpm.d/zfpm.conf
    expose:
      - 9000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M